service: wordpress
image: yourimage

# Deploy to these servers.
servers:
  web:
    hosts:
    - XXX.XXX.XXX.XXX
    options:
      add-host: host.docker.internal:host-gateway

volumes:
  - "/opt/kamal/wordpress-data:/var/www/html/public/wp-content/uploads"
  - "/opt/letsencrypt/:/letsencrypt/"

builder:
  context: .
  dockerfile: Dockerfile
  local: true
  arch: amd64
  cache:
    type: registry

registry:
  server: registry.digitalocean.com
  username: trolololo 
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
   WORDPRESS_DB_NAME: wordpress
   PHP_OPCACHE_ENABLE: 1
   SSL_MODE: "off" 
  secret:
    - WORDPRESS_DB_HOST
    - WORDPRESS_DB_USER
    - WORDPRESS_DB_PASSWORD
    - WORDPRESS_DB_NAME

accessories:
  db:
    image: mariadb:lts
    host:  XXX.XXX.XXX.XXX
    port: 3306
    env:
      clear:
        MYSQL_ROOT_HOST: '%'
      secret:
        - MARIADB_ROOT_PASSWORD
    files:
      - db/wordpress.sql:/docker-entrypoint-initdb.d/setup.sql
    volumes:
      - "/opt/kamal/mysql-data:/var/lib/mysql"
    options:
      network: "private"

proxy:
  ssl: true
  host: wordcamp.kronoscode.com
  app_port: 8080
  healthcheck:
    interval: 5
    path: "/healthcheck"

