#config/deploy.aws.yml
service: wordpress
image: yourimage

# AWS Servers
servers:
  web:
    hosts:
    - XXX.XXX.XXX.XXX
    - XXX.XXX.YYY.XXX
    - XXX.XXX.ZZZ.XXX
    - XXX.XXX.XYZ.XXX
    options:
      add-host: host.docker.internal:host-gateway
