#config/deploy.aws.yml
service: wordpress
image: yourimage

# AWS Servers
servers:
  web:
    hosts:
    - XXX.XXX.XXX.XXX
    - XXX.XXX.YYY.XXX
    - XXX.XXX.ZZZ.XXX
    - XXX.XXX.XYZ.XXX
    options:
      add-host: host.docker.internal:host-gateway
    labels:
      traefik.http.routers.wordpress-web.entrypoints: websecure
      traefik.http.routers.wordpress-web.rule: "Host(`domainname.com`)"
      traefik.http.routers.wordpress-web.tls: true
      traefik.http.services.wordpress-web.loadbalancer.server.scheme: http
      traefik.http.services.wordpress-web.loadbalancer.server.port: 8080
      traefik.http.routers.wordpress-web.tls.certresolver: letsencrypt
